#CatBurger Client Config
[Config]
	#scale
	# Default: 0.7
	# Range: 0.1 ~ 10.0
	scale = 0.6
	#float distance (blocks)
	# Default: 0.1
	# Range: 0.0 ~ 100.0
	float_distance = 0.1
	#time to complete a float cycle (tick) 
	# Default: 40.0
	# Range: 0.0 ~ 100.0
	time = 40.0
	#front & back offset
	# Default: 0.0
	# Range: -100.0 ~ 100.0
	front_back_offset = 0.0
	#vertical offset
	# Default: 0.0
	# Range: -100.0 ~ 100.0
	vertical_offset = 0.0
	#left & right offset
	# Default: -0.8
	# Range: -100.0 ~ 100.0
	left_right_offset = -0.8
