#Determines what damage source a mob needs to be killed by in order to have a chance to drop a trophy. The following values are allowed:
#ALL: allows trophies to drop whenever a mob dies. This can be to fall damage, another mob, etc.
#FAKE_PLAYER: allows trophies to drop from players and fake players. This can allow mob grinders from other mobs to drop trophies, such as the mob masher from MobGrindingUtils.
#PLAYER: only player kills will drop trophies.
#Allowed Values: ALL, FAKE_PLAYER, PLAYER
trophySourceDrop = "PLAYER"
#If true, certain trophies will not do special things when right clicked.
#This can already be changed per trophy with a datapack, but this config option remains for those who want to disable all right click behaviors for every trophy.
#Note that this will not affect mobs playing sounds when right clicked, just behaviors like the squid spawning water or rabbits dropping carrots.
globalRightClickOverride = false
#The chance a trophy will drop from its respective mob.
#All trophy drop chances are defined in their trophy json, but if you want to override that chance without going through and changing every json this is for you.
#This value works as a percentage (number * 100), so 0.2 would be a 20% chance for example.
#Set this value to any negative number to disable the override.
# Default: -1.0
# Range: -1.0 ~ 1.0
globalTrophyDropOverride = -1.0
#The chance a player will drop a trophy when killed by a charged creeper.
#This config mostly exists for singleplayer worlds where getting a player kill on a player is rather difficult.
#This value works as a percentage (number * 100), so 0.2 would be a 20% chance for example.
#Set this value to 0.0 to disable drops from charged creeper kills.
# Default: 0.2
# Range: 0.0 ~ 1.0
chargedCreeperPlayerTrophyChance = 0.2
