	###########################################################################################################
	## General settings.
	###########################################################################################################
	[Paxi.General]
		# Whether Paxi should also force-load all data packs placed in the 'datapacks' folder in the base Minecraft folder.
		# This is for compatibility with CurseForge's new data pack system.
		# Default: true
		#
		"Load from base 'datapacks' directory" = true
